
export interface Station {
  'DESKRIPZIOA-DESCRIPCION'?: any;
  'ERREPIDEA-CARRETERA'?: any;
  'GEOLOKALIZAZIOA-GEOLOCALIZACION'?: any;
  'HELBIDEA-DIRECCION'?: any;
  'IRISGARRITASUNA-ACCESIBILIDAD'?: any;
  'KALIFIKAZIO_CAS-CALIFICACION_CAS'?: any;
  'KALIFIKAZIO_EU-CALIFICACION_EU'?: any;
  'KILOMETRO_PUNTU-PUNTO_KILOMETRICO'?: any;
  'KIOSKOA_CAS-KIOSKO_CAS'?: any;
  'KIOSKOA_EU-KIOSKO_EU'?: any;
  'KODEA-CODIGO'?: any;
  'MARKESINA-MARQUESINA'?: any;
  'PANTAILA_CAS-PANTALLA_CAS'?: any;
  'PANTAILA_EU-PANTALLA_EU'?: any;
  'PROBINTZIA-PROVINCIA'?: any;
  'PROBINTZIA_KODEA-CODIGO_PROVINCIA'?: any;
  'TRAFIKO_SEINALE_CAS-SENAL_TRAFICO_CAS'?: any;
  'TRAFIKO_SEINALE_EU-SENAL_TRAFICO_EU'?: any;
  'UDALERRIA-MUNICIPIO'?: any;
  'UDALERRIA_KODEA-CODIGO_MUNICIPIO'?: any;
}
